---
version: 1
dependencies:
  galaxy: dep/requirements.yml
  python: dep/requirements.txt
  system: dep/bindep.txt

additional_build_steps:
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc